CREATE TABLE STUDENTS (ID BIGINT AUTO_INCREMENT NOT NULL, FIRST_NAME VARCHAR(35) NOT NULL, PHONE_NUMBER VARCHAR(255), BIRTH_DATE DATE NOT NULL, LAST_NAME VARCHAR(35), PRIMARY KEY (ID))
CREATE TABLE GRADES (ID BIGINT AUTO_INCREMENT NOT NULL, DISCIPLINE INTEGER NOT NULL, GRADE INTEGER NOT NULL, STUDENTS_ID BIGINT, PRIMARY KEY (ID))
ALTER TABLE GRADES ADD CONSTRAINT FK_GRADES_STUDENTS_ID FOREIGN KEY (STUDENTS_ID) REFERENCES STUDENTS (ID)
