CREATE TABLE STUDENTS (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL, FIRST_NAME VARCHAR(35) NOT NULL, PHONE_NUMBER VARCHAR(255), BIRTH_DATE DATE NOT NULL, LAST_NAME VARCHAR(35), PRIMARY KEY (ID))
CREATE TABLE GRADES (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL, DISCIPLINE INTEGER NOT NULL, GRADE INTEGER, STUDENTS_ID BIGINT, PRIMARY KEY (ID))
ALTER TABLE GRADES ADD CONSTRAINT GRADES_STUDENTS_ID FOREIGN KEY (STUDENTS_ID) REFERENCES STUDENTS (ID)
